"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from .base import *  # noqa
from .database import *  # noqa
from .localization import *  # noqa
from .logging import *  # noqa
from .rosetta import *  # noqa
