"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from corsheaders.defaults import default_headers, default_methods
from decouple import config
from django.core.management.utils import get_random_secret_key

__all__ = (
    "APP_NAME",
    "BASE_DIR",
    "SECRET_KEY",
    "DEBUG",
    "ALLOWED_HOSTS",
    "SECURE_PROXY_SSL_HEADER",
    "CSRF_TRUSTED_ORIGINS",
    "DEFAULT_AUTO_FIELD",
    "SECURE_SSL_REDIRECT",
    "SESSION_COOKIE_SECURE",
    "WSGI_APPLICATION",
    "ASGI_APPLICATION",
    "ROOT_URLCONF",
    "CORS_ALLOWED_ORIGINS",
    "CORS_ALLOW_HEADERS",
    "CORS_ALLOW_METHODS",
    "CORS_ALLOW_CREDENTIALS",
    "REDIS_HOST",
    "REDIS_PORT",
    "CACHES",
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(os.path.join(BASE_DIR, "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


APP_NAME = config("DJANGO_APP_NAME", default="AppName")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool, default=True)


SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="",
    cast=lambda v: [x for s in v.split(",") if (x := s.strip())],  # new optimized
    # cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],  # old
)


CSRF_TRUSTED_ORIGINS = config(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default="",
    cast=lambda v: [x for s in v.split(",") if (x := s.strip())],
)

CORS_ALLOWED_ORIGINS = config(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default="",
    cast=lambda v: [x for s in v.split(",") if (x := s.strip())],
)

CORS_ALLOW_HEADERS = (
    *default_headers,
    # "my-custom-header",
)

CORS_ALLOW_METHODS = (
    *default_methods,
    # "POKE",
)

CORS_ALLOW_CREDENTIALS = True


WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


ROOT_URLCONF = "config.urls"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REDIS_HOST = config("REDIS_HOST", default="redis")
REDIS_PORT = config("REDIS_PORT", default=6379, cast=int)
# REDIS_DB = config("REDIS_DB")
# REDIS_PASSWORD = config("REDIS_PASSWORD")


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
        "TIMEOUT": 600,
    }
}
