__all__ = (
    "ROSETTA_MESSAGES_PER_PAGE",
    "ROSETTA_SHOW_AT_ADMIN_PANEL",
    "ROSETTA_ACCESS_CONTROL_FUNCTION",
)

ROSETTA_MESSAGES_PER_PAGE = 20
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_ACCESS_CONTROL_FUNCTION = "users.utils.rosetta_access_control"
